config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sangria-rat.sh
        container: qc.acc_sunny-zucchini-akbash
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-lilac-cheetah.sh
        container: qc.doc_fuzzy-goldenrod-dachsbracke
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-copper-devil.sh
        container: qc.doc_wiggy-yellow-akita
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ochre-toucan.sh
        container: qc.doc_scaly-copper-macaw
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-sangria-bat.sh
        container: qc.lic_pokey-lime-crab
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-olive-otter.sh
        container: qc.sec_homely-chocolate-emu
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-amber-tarantula.sh
        container: qc.sty_tacky-copper-harrier
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-periwinkle-deer.sh
        container: qc.ver_shaggy-cinnabar-stingray
timeout: 5400
