config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-aquamarine-cat.sh
        container: qc.acc_greasy-peach-jellyfish
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-orange-slug.sh
        container: qc.doc_chummy-eggplant-cougar
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-russet-greyhound.sh
        container: qc.doc_frumpy-tangerine-toad
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-bronze-impala.sh
        container: qc.doc_trippy-pear-discus
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-blue-barracuda.sh
        container: qc.lic_boozy-saffron-civet
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-periwinkle-molly.sh
        container: qc.sec_flimsy-ivory-kakapo
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-aquamarine-tamarin.sh
        container: qc.sty_bluesy-lime-centipede
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-white-emu.sh
        container: qc.ver_woozy-zucchini-alligator
timeout: 5400
