config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells:
      branch: test-licence
      repo: https://gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-jade-angelfish.sh
        container: qc.acc_droopy-copper-octopus
  QC.Doc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-charcoal-affenpinscher.sh
        container: qc.doc_surly-linen-oriole
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-linen-squid.sh
        container: qc.doc_hilly-dandelion-octopus
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnabar-ostrich.sh
        container: qc.doc_smelly-red-badger
  QC.Lic:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cardinal-wasp.sh
        container: qc.lic_chewy-black-angelfish
  QC.Sec:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cyan-centipede.sh
        container: qc.sec_pokey-ultramarine-chin
  QC.Sty:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cyan-flamingo.sh
        container: qc.sty_skanky-coral-tarsier
  QC.Ver:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-corn-meerkat.sh
        container: qc.ver_pokey-taupe-cheetah
timeout: 5400
