config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-persimmon-vole.sh
        container: qc.acc_squeaky-lemon-avocet
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-harlequin-sloth.sh
        container: qc.doc_flaky-aquamarine-termite
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cornflower-dachsbracke.sh
        container: qc.doc_gloppy-indigo-mole
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-silver-bee.sh
        container: qc.doc_stuffy-maroon-albatross
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-buzzard.sh
        container: qc.lic_squirrely-alizarin-anteater
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-teal-russel.sh
        container: qc.sec_nippy-salmon-quail
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-turquoise-cheetah.sh
        container: qc.sty_bumpy-celadon-shrimp
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-goldenrod-slug.sh
        container: qc.ver_gamy-maroon-grouse
timeout: 5400
