config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells:
      branch: test-licence
      repo: https://gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ultramarine-robin.sh
        container: qc.acc_fuzzy-sapphire-eel
  QC.Doc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-brown-bat.sh
        container: qc.doc_pokey-magnolia-vulture
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-sapphire-booby.sh
        container: qc.doc_smelly-plum-owl
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-silver-iguana.sh
        container: qc.doc_tasty-champagne-newfoundland
  QC.Lic:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-tomato-barnacle.sh
        container: qc.lic_woolly-grey-earwig
  QC.Met:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rose-dalmatian.sh
        container: qc.met_cranky-blue-chimpanzee
  QC.Sec:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-platinum-devil.sh
        container: qc.sec_queasy-turquoise-mongrel
  QC.Sty:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-linen-goose.sh
        container: qc.sty_randy-cardinal-seal
  QC.Ver:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-sangria-impala.sh
        container: qc.ver_leaky-black-neanderthal
timeout: 5400
