config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells:
      branch: test-licence
      repo: https://gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chestnut-fossa.sh
        container: qc.acc_snoopy-apricot-paradise
  QC.Doc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-charcoal-cow.sh
        container: qc.doc_scaly-burgundy-rottweiler
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-mustard-mayfly.sh
        container: qc.doc_lumpy-orange-sheep
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-linen-dachsbracke.sh
        container: qc.doc_freaky-vermilion-turtle
  QC.Lic:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-turquoise-angora.sh
        container: qc.lic_lanky-rust-retriever
  QC.Met:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wheat-cougar.sh
        container: qc.met_blurry-mustard-booby
  QC.Sec:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-linen-reindeer.sh
        container: qc.sec_stuffy-zucchini-walrus
  QC.Sty:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-heliotrope-retriever.sh
        container: qc.sty_sickly-apricot-caiman
  QC.Ver:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-red-manatee.sh
        container: qc.ver_stealthy-blue-tetra
timeout: 5400
