config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells:
      branch: test-licence
      repo: https://gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-violet-tuatara.sh
        container: qc.acc_wiggy-tomato-mammoth
  QC.Doc:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pink-flamingo.sh
        container: qc.doc_shaggy-burgundy-chameleon
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-brass-gecko.sh
        container: qc.doc_bumpy-flax-newfoundland
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-salmon-dachshund.sh
        container: qc.doc_paltry-magenta-bison
  QC.Lic:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-grey-beaver.sh
        container: qc.lic_shaggy-smalt-salamander
  QC.Sec:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-rose-woodlouse.sh
        container: qc.sec_chewy-aquamarine-octopus
  QC.Sty:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bistre-loon.sh
        container: qc.sty_flaky-harlequin-seahorse
  QC.Ver:
    repos:
      gricad-gitlab.univ-grenoble-alpes.fr/schaeffn/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-teal-kudu.sh
        container: qc.ver_crabby-flax-jackal
timeout: 5400
