config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-tomato-buffalo.sh
        container: qc.acc_sleazy-denim-burmese
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-fuchsia-chicken.sh
        container: qc.doc_droopy-goldenrod-cat
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-raccoon.sh
        container: qc.doc_pretty-white-octopus
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-eggplant-fly.sh
        container: qc.doc_sleazy-pear-husky
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-coral-buffalo.sh
        container: qc.lic_crabby-magnolia-coati
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-xanthic-mongoose.sh
        container: qc.sec_shaky-beige-sparrow
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-buff-saola.sh
        container: qc.sty_hilly-apricot-jaguar
  QC.Uni:
    repos:
      bitbucket.org/nschaeff/xshells pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-olivine-quokka.sh
        container: qc.uni_lumpy-olive-chinook
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-tomato-malamute.sh
        container: qc.ver_sleazy-indigo-warthog
timeout: 5400
