config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-sapphire-yak.sh
        container: qc.acc_fuzzy-pear-mastiff
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-buff-crane.sh
        container: qc.doc_shaky-grey-dachshund
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cerulean-squirrel.sh
        container: qc.doc_geeky-burgundy-goose
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-salmon-camel.sh
        container: qc.doc_stinky-khaki-snail
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cerulean-cow.sh
        container: qc.lic_messy-seashell-mau
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ultramarine-turtle.sh
        container: qc.sec_jumpy-indigo-macaw
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-champagne-angelfish.sh
        container: qc.sty_goopy-green-centipede
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-chartreuse-dollar.sh
        container: qc.ver_shaky-chocolate-moth
timeout: 5400
