config:
  credentials: []
  project_repos:
    bitbucket.org/nschaeff/xshells:
      branch: master
      repo: https://bitbucket.org/nschaeff/xshells
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-corn-cuttlefish.sh
        container: qc.acc_gamy-cardinal-ragdoll
  QC.Doc:
    repos:
      bitbucket.org/nschaeff/xshells find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-periwinkle-liger.sh
        container: qc.doc_squeaky-chocolate-ladybird
      bitbucket.org/nschaeff/xshells git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sapphire-hippopotamus.sh
        container: qc.doc_craggy-cobalt-shrimp
      bitbucket.org/nschaeff/xshells markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cardinal-dog.sh
        container: qc.doc_homey-purple-newt
  QC.Lic:
    repos:
      bitbucket.org/nschaeff/xshells licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-razzmatazz-cuttlefish.sh
        container: qc.lic_muzzy-turquoise-angora
  QC.Sec:
    repos:
      bitbucket.org/nschaeff/xshells bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ecru-foxhound.sh
        container: qc.sec_frumpy-plum-caterpillar
  QC.Sty:
    repos:
      bitbucket.org/nschaeff/xshells flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-magnolia-alligator.sh
        container: qc.sty_freaky-tangerine-eagle
  QC.Ver:
    repos:
      bitbucket.org/nschaeff/xshells get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-tangerine-cow.sh
        container: qc.ver_baggy-cerise-buzzard
timeout: 5400
